### ISSUE TITLE
Advise user about, or install OS required packages if not present.

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#108]
Detect and suggest/install the following packages in the setup phase:
- libffi-dev
- libssl-dev
- python-dev

This will fix the issues raised in #104.

**Comment by Ant1r** [comment]
Please also advise that gpg is needed (on OSX GPG_Suite) ; if gpg isn't installed, deken currently crashes with cryptic logs.

**Comment by umlaeute** [comment]
what's the "cryptic logs"? deken should never crash.

**Comment by Ant1r** [comment]
Well, cryptic for a non python coder at least :

~/bin/deken package -v 0.3.2 moonlib
Deken 0.1
Packaging moonlib-v0.3.2-(Darwin-i386-32)(Darwin-x86_64-32)-externals.tar.gz
Attempting to GPG sign 'moonlib-v0.3.2-(Darwin-i386-32)(Darwin-x86_64-32)-externals.tar.gz'
Traceback (most recent call last):
  File "/Users/matt/.deken/virtualenv/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/Users/matt/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/Users/matt/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/Users/matt/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/Users/matt/.deken/virtualenv/lib/python2.7/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/Users/matt/.deken/deken.hy", line 672, in <module>
    
  File "/Users/matt/.deken/deken.hy", line 394, in main
    (defn main []
  File "/Users/matt/.deken/deken.hy", line 650, in _hy_anon_fn_63
    
  File "/Users/matt/.deken/deken.hy", line 412, in _hy_anon_fn_62
    (command arguments))))
  File "/Users/matt/.deken/deken.hy", line 352, in _hy_anon_fn_57
    (let [[package-filename (make-archive-basename args.source args.version)]]
  File "/Users/matt/.deken/deken.hy", line 608, in _hy_anon_fn_56
    
  File "/Users/matt/.deken/deken.hy", line 356, in _hy_anon_fn_55
    (gpg-sign-file archive-filename)
  File "/Users/matt/.deken/deken.hy", line 237, in gpg_sign_file
    (defn gpg-sign-file [filename]
  File "/Users/matt/.deken/deken.hy", line 243, in _hy_anon_fn_37
    (do-gpg-sign-file filename signfile))))
  File "/Users/matt/.deken/deken.hy", line 458, in do_gpg_sign_file
    
  File "/Users/matt/.deken/deken.hy", line 467, in _hy_anon_fn_35
    
  File "/Users/matt/.deken/virtualenv/lib/python2.7/site-packages/gnupg.py", line 680, in __init__
    p = self._open_subprocess(["--version"])
  File "/Users/matt/.deken/virtualenv/lib/python2.7/site-packages/gnupg.py", line 726, in _open_subprocess
    return Popen(cmd, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
