### ISSUE TITLE
keyring error from python

### ISSUE THREAD

**Issue by derekxkwan** [pure-data/deken#178]
running into an error on trying to use deken upload after entering my username at the prompt. here's the full traceback:

```
Traceback (most recent call last):
  File "/home/dxk/.deken/virtualenv/bin/hy", line 11, in <module>
    sys.exit(hy_main())
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 342, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 330, in cmdline_handler
    return run_file(options.args[0])
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 212, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 185, in pretty_error
    return func(*args, **kw)
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/hy/importer.py", line 79, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/home/dxk/.deken/deken.hy", line 863, in <module>
    
  File "/home/dxk/.deken/deken.hy", line 603, in main
    (if command (command arguments) (.print_help arg-parser)))
  File "/home/dxk/.deken/deken.hy", line 553, in _hy_anon_fn_60
    (setv password (get-upload-password username args.ask-password))
  File "/home/dxk/.deken/deken.hy", line 790, in get_upload_password
    
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/keyring/core.py", line 41, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/dxk/.deken/virtualenv/local/lib/python2.7/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.

```

This is from the deken I just curled (and removed my ~/.deken folder). For kicks, also tried to sudo pip and pip3 install secretstorage and keyrings.alt (as per the error) but nothing changed. I'm on Ubuntu 16.04.3 LTS.  I have been able to upload before without the error popping up.

**Comment by umlaeute** [comment]
you might want to do as suggested, and install the `keyrings.alt` package.

**Comment by derekxkwan** [comment]
all is good, thx!
