### ISSUE TITLE
"deken install" crashes on macOS

### ISSUE THREAD

**Issue by jamiebullock** [pure-data/deken#217]
Steps to reproduce:

- Create a Deken package with `deken package foo -v 1.0` 
- Attempt to install with `deken install foo` or `deken install foo[v1.0](Darwin-x86_64-32).dek`

Expected:

- The package installs

Actual:

- The following TraceBack is printed:

```
Traceback (most recent call last):
  File "/Users/jamie/.deken/virtualenv/bin/hy", line 11, in <module>
    sys.exit(hy_main())
  File "/Users/jamie/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 346, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/Users/jamie/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 334, in cmdline_handler
    return run_file(options.args[0])
  File "/Users/jamie/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 213, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "/Users/jamie/.deken/virtualenv/lib/python2.7/site-packages/hy/cmdline.py", line 186, in pretty_error
    return func(*args, **kw)
  File "/Users/jamie/.deken/virtualenv/lib/python2.7/site-packages/hy/importer.py", line 93, in import_file_to_module
    module = imp.load_compiled(module_name, bytecode_path)
  File "/Users/jamie/.deken/deken.hy", line 2581, in <module>
    
  File "/Users/jamie/.deken/deken.hy", line 1809, in main
    (if command (command arguments) (.print_help arg-parser)))
  File "/Users/jamie/.deken/deken.hy", line 1587, in _hy_anon_var_244
    (setv pkgs (.union (set args.package) (reqs2pkgs args.requirement)))
  File "/Users/jamie/.deken/deken.hy", line 1586, in reqs2pkgs
    (chain.from-iterable (list-comp (req2pkg f) [f reqs])))
TypeError: 'NoneType' object is not iterable
```

**Comment by umlaeute** [comment]
which version of `deken` are you using?

is this still a problem with recent versions? (not that i changed anything on purpose, but you never now...)

**Comment by umlaeute** [comment]
i've now added an `install` test to our CI builds, and it seems [the problem is gone](https://git.iem.at/pd/deken/-/jobs/23921#L95), at least with `deken-0.7.2`
