### ISSUE TITLE
deken install crashes in Ubuntu 12.04LTS

### ISSUE THREAD

**Issue by emviveros** [pure-data/deken#224]
After running the commands in deken repository's README.md [Get started](https://github.com/pure-data/deken/blob/master/developer/README.md#get-started) self installation fails returning this message:

```
This is your first time running deken on this machine.
I'm going to install myself and my dependencies into /home/pi/.deken now.
Feel free to Ctrl-C now if you don't want to do this.
Installing deken.
Fetching Python requirements file: https://raw.githubusercontent.com/pure-data/deken/master/developer/requirements.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   159  100   159    0     0    471      0 --:--:-- --:--:-- --:--:--   470
Fetching main hylang file: https://raw.githubusercontent.com/pure-data/deken/master/developer/deken.hy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82854  100 82854    0     0   143k      0 --:--:-- --:--:-- --:--:--  143k
Downloading & installing Virtualenv for 3.6 using https://bootstrap.pypa.io/virtualenv/3.6/virtualenv.pyz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6648k  100 6648k    0     0  2553k      0  0:00:02  0:00:02 --:--:-- 2552k
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.deken/virtualenv.pyz/__main__.py", line 168, in <module>
  File "/home/pi/.deken/virtualenv.pyz/__main__.py", line 162, in run
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/__init__.py", line 3, in <module>
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/run/__init__.py", line 12, in <module>
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 6, in <module>
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/create/creator.py", line 15, in <module>
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/discovery/cached_py_info.py", line 16, in <module>
  File "/home/pi/.deken/virtualenv.pyz/virtualenv/discovery/py_info.py", line 16, in <module>
ImportError: cannot import name 'dist'
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues
```

Thanks for any advance!

**Comment by emviveros** [comment]
Solved installing the package python3-distutils:

```
sudo apt install python3-distutils
```
