### ISSUE TITLE
search for arch=Sources fails

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#257]
i can search for the Sources of a package:

~~~sh
$ deken find --arch=Sources zexy
zexy/2.4.1 uploaded by zmoelnigbot on 2022-02-02 17:14:25 for Sources
	 URL: http://puredata.info/Members/zmoelnigbot/software/zexy/2.4.1/zexy[v2.4.1](Sources).dek
	 -----------------------------------------------------------------
~~~

however, doing a generic search for all *Source* packages fails:

~~~sh
$ deken find --arch=Sources 
Traceback (most recent call last):
  File "/usr/bin/hy", line 12, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<<PATH>>/deken.hy", line 2038, in <module>
    (main)
  File "<<PATH>>/deken.hy", line 2034, in main
    (if command (command arguments) (.print_help arg-parser)))
  File "<<PATH>>/deken.hy", line 1398, in find
    (find-packages searchterms
  File "<<PATH>>/deken.hy", line 1362, in find_packages
    (filter-older-versions
  File "<<PATH>>/deken.hy", line 971, in filter_older_versions
    (doit libdicts depth)
  File "<<PATH>>/deken.hy", line 965, in doit
    (+ result (cut (sorted (get pkgdict key)
TypeError: '<' not supported between instances of 'str' and 'NoneType'
~~~

**Comment by umlaeute** [comment]
it seems that the underlying issue is a problem with packages that lack a version number.

There is a [gigaverb~](http://puredata.info/Members/dis/software/gigaverb~/gigaverb~(Darwin-i386-32)(Sources)(Darwin-x86_64-32)-externals.tar.gz) upload for Darwin-386-32/Darwin-amd64-32/Sources but no version number, and this fails to sort.

i can also trigger the problem with other architecture, e.g.

~~~sh
 deken search --libraries --arch "Darwin-i386-32" "gigaverb*"   |& sed -e 's|/home/zmoelnig/src/puredata/deken/developer|<<PATH>>|g'
Traceback (most recent call last):
  File "/home/zmoelnig/.deken/virtualenv/bin/hy", line 8, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zmoelnig/.deken/deken.hy", line 1912, in <module>
    (main)
  File "/home/zmoelnig/.deken/deken.hy", line 1908, in main
    (if command (command arguments) (.print_help arg-parser)))
  File "/home/zmoelnig/.deken/deken.hy", line 1330, in find
    (find-packages searchterms
  File "/home/zmoelnig/.deken/deken.hy", line 1294, in find_packages
    (filter-older-versions
  File "/home/zmoelnig/.deken/deken.hy", line 906, in filter_older_versions
    (doit libdicts depth)
  File "/home/zmoelnig/.deken/deken.hy", line 900, in doit
    (+ result (cut (sorted (get pkgdict key)
TypeError: '<' not supported between instances of 'str' and 'NoneType'
~~~
