### ISSUE TITLE
Python 3.10 breaks hy breaks Deken

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#259]
Installing or executing  deken according to the developer's readme (Section: Manual bootstrap) fails on systems with Python 3.10 installed. This is on:
  * Ubuntu 22.04
  * Python 3.10.4

The issue seems to be related to https://github.com/hylang/hy/issues/2061
 
Here is the deken installation  log:

```
roman@nl-11841:~$ deken
This is your first time running deken on this machine.
I'm going to install myself and my dependencies into /home/roman/.deken now.
Feel free to Ctrl-C now if you don't want to do this.
Installing deken.
Fetching Python requirements file: https://raw.githubusercontent.com/pure-data/deken/master/developer/requirements.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   159  100   159    0     0    499      0 --:--:-- --:--:-- --:--:--   501
Fetching main hylang file: https://raw.githubusercontent.com/pure-data/deken/master/developer/deken.hy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 88901  100 88901    0     0   275k      0 --:--:-- --:--:-- --:--:--  275k
Downloading & installing Virtualenv for 3.10 using https://bootstrap.pypa.io/virtualenv/3.10/virtualenv.pyz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.8M  100 10.8M    0     0  15.1M      0 --:--:-- --:--:-- --:--:-- 15.1M
created virtual environment CPython3.10.4.final.0-64 in 152ms
  creator CPython3Posix(dest=/home/roman/.deken/virtualenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/roman/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Installing deken library dependencies.
Collecting hy~=0.19
  Using cached hy-0.20.0-py2.py3-none-any.whl (83 kB)
Collecting easywebdav2~=1.3
  Using cached easywebdav2-1.3.0-py2.py3-none-any.whl (5.1 kB)
Collecting pyelftools~=0.26
  Using cached pyelftools-0.28-py2.py3-none-any.whl (155 kB)
Collecting macholib~=1.14
  Using cached macholib-1.16-py2.py3-none-any.whl (37 kB)
Collecting pefile==2019.4.18
  Using cached pefile-2019.4.18-py3-none-any.whl
Collecting python-gnupg~=0.4
  Using cached python_gnupg-0.4.8-py2.py3-none-any.whl (18 kB)
Collecting keyring~=21.4
  Using cached keyring-21.8.0-py3-none-any.whl (32 kB)
Collecting ndg_httpsclient==0.5.1
  Using cached ndg_httpsclient-0.5.1-py3-none-any.whl (34 kB)
Collecting pyasn1~=0.4
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pyopenssl~=19.1
  Using cached pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting rply>=0.7.7
  Using cached rply-0.7.8-py2.py3-none-any.whl (16 kB)
Collecting astor>=0.8
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting funcparserlib>=0.3.6
  Using cached funcparserlib-0.3.6-py3-none-any.whl
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting altgraph>=0.15
  Using cached altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
Collecting SecretStorage>=3.2
  Using cached SecretStorage-3.3.2-py3-none-any.whl (15 kB)
Collecting jeepney>=0.4.2
  Using cached jeepney-0.8.0-py3-none-any.whl (48 kB)
Collecting cryptography>=2.8
  Using cached cryptography-37.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: python-gnupg, pyelftools, pyasn1, funcparserlib, certifi, appdirs, altgraph, urllib3, six, rply, pycparser, macholib, jeepney, idna, future, colorama, charset-normalizer, astor, requests, pefile, hy, cffi, easywebdav2, cryptography, SecretStorage, pyopenssl, ndg_httpsclient, keyring
Successfully installed SecretStorage-3.3.2 altgraph-0.17.2 appdirs-1.4.4 astor-0.8.1 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 colorama-0.4.4 cryptography-37.0.1 easywebdav2-1.3.0 funcparserlib-0.3.6 future-0.18.2 hy-0.20.0 idna-3.3 jeepney-0.8.0 keyring-21.8.0 macholib-1.16 ndg_httpsclient-0.5.1 pefile-2019.4.18 pyasn1-0.4.8 pycparser-2.21 pyelftools-0.28 pyopenssl-19.1.0 python-gnupg-0.4.8 requests-2.27.1 rply-0.7.8 six-1.16.0 urllib3-1.26.9
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 268, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
hy.errors.HyEvalError: 
  File "[HyExpression([
  HySymbol('import'),
  HySymbol('hy')]), HyExpression([
  HyExpression([
    HySymbol('hy.macros.macro'),
    HyString('defmacro')]),
  HyExpression([
    HySymbol('fn'),
    HyList([
      HySymbol('&name'),
      HySymbol('macro-name'),
      HySymbol('lambda-list'),
      HySymbol('&rest'),
      HySymbol('body')]),
    HyString('the defmacro macro'),
    HyExpression([
      HySymbol('if*'),
      HyExpression([
        HySymbol('not'),
        HyExpression([
          HySymbol('isinstance'),
          HySymbol('macro-name'),
          HySymbol('hy.models.HySymbol')])]),
      HyExpression([
        HySymbol('raise'),
        HyExpression([
          HySymbol('hy.errors.HyTypeError'),
          HyExpression([
            HySymbol('%'),
            HyString("received a `%s' instead of a symbol for macro name"),
            HyExpression([
              HySymbol('.'),
              HyExpression([
                HySymbol('type'),
                HySymbol('name')]),
              HySymbol('__name__')])]),
          HySymbol('None'),
          HySymbol('--file--'),
          HySymbol('None')])])]),
    HyExpression([
      HySymbol('for'),
      HyList([
        HySymbol('kw'),
        HyExpression([
          HySymbol('quote'),
          HyList([
            HySymbol('&kwonly'),
            HySymbol('&kwargs')])])]),
      HyExpression([
        HySymbol('if*'),
        HyExpression([
          HySymbol('in'),
          HySymbol('kw'),
          HySymbol('lambda-list')]),
        HyExpression([
          HySymbol('raise'),
          HyExpression([
            HySymbol('hy.errors.HyTypeError'),
            HyExpression([
              HySymbol('%'),
              HyString('macros cannot use %s'),
              HySymbol('kw')]),
            HySymbol('macro-name'),
            HySymbol('--file--'),
            HySymbol('None')])])])]),
    HyExpression([
      HySymbol('quasiquote'),
      HyExpression([
        HySymbol('eval-and-compile'),
        HyExpression([
          HySymbol('import'),
          HySymbol('hy')]),
        HyExpression([
          HyExpression([
            HySymbol('hy.macros.macro'),
            HyExpression([
              HySymbol('unquote'),
              HyExpression([
                HySymbol('str'),
                HySymbol('macro-name')])])]),
          HyExpression([
            HySymbol('fn'),
            HyExpression([
              HySymbol('unquote'),
              HyExpression([
                HySymbol('+'),
                HyExpression([
                  HySymbol('quasiquote'),
                  HyList([
                    HySymbol('&name')])]),
                HySymbol('lambda-list')])]),
            HyExpression([
              HySymbol('unquote-splice'),
              HySymbol('body')])])])])])])])]", line 1
    ;;; Hy bootstrap macros
    ^---------------------^
required field "lineno" missing from alias

```

**Comment by umlaeute** [comment]
what do you suggest?
(what can we do on the `deken` side?)

**Comment by umlaeute** [comment]
the problem is, that `hy` is still a moving target (and there are no actually released versions), and i think they will introduce another bunch of breaking changes before the final hy-1.0 release.

options to use deken right now:
- use `buster` :disappointed: 
- somehow force deken to use Python3.9 (Python3.9 is currently shipped with Debian/bullseye; I don't know whether it will be shipped with Debian/bookworm).
  something like this might work for installing `deken` into your home
  ```sh
  PYTHON_BIN=python3.9 ./deken install
  ```
  (this will stop with "*self-'install' not implemented for this platform!*", but otherwise it seems to work)
- use Docker:
  ```sh
   docker pull registry.git.iem.at/pd/deken:latest
   ```
   and then:
   ```sh
   docker run --rm -ti -u ${UID} -v "$(pwd):/deken" registry.git.iem.at/pd/deken:latest deken --help
   ```
   (wou'll probably want to wrap that last command into a wrapper)

**Comment by reduzent** [comment]
Thanks for all the suggestion. I actually have docker deken running. The only thin that still bugs me is that I have to run the docker container as root. But that's probably a docker specific issue I haven't investigated yet.

Should we close this as 'wontfix'?

**Comment by umlaeute** [comment]
> I have to run the docker container as root.

how so? my example above shows how to run it as a user.
(provided, that the user is allowed to run Docker containers).

what does not work is gpg-signing inside the container (though i haven't actually checked what would be required to make it work)

**Comment by reduzent** [comment]
It works on Ubuntu 22.10 now. Sweet!
