### ISSUE TITLE
troubles installing deken cmdline on mac m1

### ISSUE THREAD

**Issue by patricecolet** [pure-data/deken#281]
% developer/deken upgrade --self
This is your first time running deken on this machine.
I'm going to install myself and my dependencies into /Users/patricecolet/.deken now.
Feel free to Ctrl-C now if you don't want to do this.
Installing deken.
Fetching Python requirements file: https://raw.githubusercontent.com/pure-data/deken/main/developer/requirements.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   105  100   105    0     0    539      0 --:--:-- --:--:-- --:--:--   570
Fetching main hylang file: https://raw.githubusercontent.com/pure-data/deken/main/developer/deken.hy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 98059  100 98059    0     0   268k      0 --:--:-- --:--:-- --:--:--  275k
Downloading & installing Virtualenv for 3.10 using https://bootstrap.pypa.io/virtualenv/3.10/virtualenv.pyz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.4M  100 10.4M    0     0  1243k      0  0:00:08  0:00:08 --:--:-- 1304k
fail
Traceback (most recent call last):
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 82, in _get
    result = get_wheel(
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 23, in get_wheel
    wheel = from_bundle(distribution, version, for_py_version, search_dirs, app_data, do_periodic_update, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/bundle.py", line 17, in from_bundle
    wheel = periodic_update(distribution, of_version, for_py_version, wheel, search_dirs, app_data, per, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 35, in periodic_update
    handle_auto_update(distribution, for_py_version, wheel, search_dirs, app_data, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 69, in handle_auto_update
    embed_update_log.write(u_log.to_dict())
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 154, in write
    self.file.write_text(json.dumps(content, sort_keys=True, indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/Users/patricecolet/Library/Application Support/virtualenv/wheel/3.10/embed/3/setuptools.json'
fail
Traceback (most recent call last):
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 82, in _get
    result = get_wheel(
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 23, in get_wheel
    wheel = from_bundle(distribution, version, for_py_version, search_dirs, app_data, do_periodic_update, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/bundle.py", line 17, in from_bundle
    wheel = periodic_update(distribution, of_version, for_py_version, wheel, search_dirs, app_data, per, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 35, in periodic_update
    handle_auto_update(distribution, for_py_version, wheel, search_dirs, app_data, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 69, in handle_auto_update
    embed_update_log.write(u_log.to_dict())
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 154, in write
    self.file.write_text(json.dumps(content, sort_keys=True, indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/Users/patricecolet/Library/Application Support/virtualenv/wheel/3.10/embed/3/wheel.json'
fail
Traceback (most recent call last):
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 82, in _get
    result = get_wheel(
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 23, in get_wheel
    wheel = from_bundle(distribution, version, for_py_version, search_dirs, app_data, do_periodic_update, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/bundle.py", line 17, in from_bundle
    wheel = periodic_update(distribution, of_version, for_py_version, wheel, search_dirs, app_data, per, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 35, in periodic_update
    handle_auto_update(distribution, for_py_version, wheel, search_dirs, app_data, env)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 69, in handle_auto_update
    embed_update_log.write(u_log.to_dict())
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 154, in write
    self.file.write_text(json.dumps(content, sort_keys=True, indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/Users/patricecolet/Library/Application Support/virtualenv/wheel/3.10/embed/3/pip.json'
fail
Traceback (most recent call last):
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 82, in _get
    result = get_wheel(
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 37, in get_wheel
    add_wheel_to_update_log(wheel, for_py_version, app_data)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 83, in add_wheel_to_update_log
    embed_update_log.write(u_log.to_dict())
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 154, in write
    self.file.write_text(json.dumps(content, sort_keys=True, indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/Users/patricecolet/Library/Application Support/virtualenv/wheel/3.10/embed/3/wheel.json'
PermissionError(13, 'Permission denied')
fail
Traceback (most recent call last):
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 82, in _get
    result = get_wheel(
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 37, in get_wheel
    add_wheel_to_update_log(wheel, for_py_version, app_data)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 83, in add_wheel_to_update_log
    embed_update_log.write(u_log.to_dict())
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 154, in write
    self.file.write_text(json.dumps(content, sort_keys=True, indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/Users/patricecolet/Library/Application Support/virtualenv/wheel/3.10/embed/3/pip.json'
PermissionError(13, 'Permission denied')
fail
Traceback (most recent call last):
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 82, in _get
    result = get_wheel(
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 37, in get_wheel
    add_wheel_to_update_log(wheel, for_py_version, app_data)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 83, in add_wheel_to_update_log
    embed_update_log.write(u_log.to_dict())
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 154, in write
    self.file.write_text(json.dumps(content, sort_keys=True, indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/Users/patricecolet/Library/Application Support/virtualenv/wheel/3.10/embed/3/setuptools.json'
PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/patricecolet/.deken/virtualenv.pyz/__main__.py", line 167, in <module>
  File "/Users/patricecolet/.deken/virtualenv.pyz/__main__.py", line 163, in run
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/__main__.py", line 16, in run
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/run/__init__.py", line 30, in cli_run
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/run/session.py", line 43, in run
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/run/session.py", line 56, in _seed
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 40, in run
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/patricecolet/.deken/virtualenv.pyz/virtualenv/seed/embed/via_app_data/via_app_data.py", line 125, in _get_seed_wheels
RuntimeError: seed failed due to failing to download wheels wheel, pip, setuptools
Installing deken library dependencies.
developer/deken: line 202: /Users/patricecolet/.deken/virtualenv/bin/pip: No such file or directory
Installation of requirements failed.
You probably should install the following packages first:
 - 'python3-dev'
 - 'libffi-dev'
 - 'libssl-dev'

**Comment by patricecolet** [comment]
% sudo developer/deken upgrade --self 

has resolved this issue

**Comment by umlaeute** [comment]
weird. `sudo` should not be necessary. but I think the issue is really about macOS runtime permissions (that is: Apple prevents protects you from modifying your own files when using the Terminal)

**Comment by patricecolet** [comment]
I think it's even worse because the downloaded files in ~/.deken are owned by root now

**Comment by umlaeute** [comment]
Well, you can always run `sudo chown -R patricecolet ~/.deken`...
