### ISSUE TITLE
deken package --objects crash

### ISSUE THREAD

**Issue by Ant1r** [pure-data/deken#289]
Ubuntu 20.40 ; python 3.8.10 ; deken 0.9.7 (just upgraded/updated)

``` sh
$ deken package --objects ../pof.dek.txt --version ${POF_VERSION} pof
Traceback (most recent call last):
  File "/home/antoine/.deken/virtualenv/bin/hy", line 8, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/antoine/.deken/deken.hy", line 2199, in <module>
    (try
  File "/home/antoine/.deken/deken.hy", line 2195, in main
    (log.debug (.join " " sys.argv))
  File "/home/antoine/.deken/deken.hy", line 1670, in <lambda>
    ;; zip up a set of built externals
  File "/home/antoine/.deken/deken.hy", line 1637, in package
    (set-default-floatsize args.default-floatsize)
  File "/home/antoine/.deken/deken.hy", line 1640, in <listcomp>
    ;; if asking for a directory just package it up
  File "/home/antoine/.deken/deken.hy", line 1269, in archive_extra
    (if (dekfile.endswith ".dek")
  File "/home/antoine/.deken/deken.hy", line 804, in make_objects_file
    dekfilename)
  File "/home/antoine/.deken/deken.hy", line 791, in do_make_objects_file
    (or
  File "/home/antoine/.deken/deken.hy", line 767, in genobjs
    (defn genobjs [input]
TypeError: 'NoneType' object is not iterable
```

If the `--object` flag is not used, or if the `.dek.txt` file already exists, the crash doesn't happen.

**Comment by umlaeute** [comment]
could you post the `../pof.dek.txt` file so i could try to reproduce the issue?

**Comment by Ant1r** [comment]
[pof.dek.txt](https://github.com/pure-data/deken/files/11235287/pof.dek.txt)

**Comment by Ant1r** [comment]
thanks! that actually fixes my crash.

**Comment by umlaeute** [comment]
thought so :-)
