### ISSUE TITLE
UnicodeDecodeError on tty

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#71]
When running `deken package -v1.0 mypkg` on the console, the program aborts with a `UnicodeDecodeError` exception:

```python
Deken 0.1
Packaging into stdout-v0.1-(Linux-amd64-64)-externals
Attempting to GPG sign 'stdout-v0.1-(Linux-amd64-64)-externals.tar.gz'
Traceback (most recent call last):
  File "/usr/bin/hy2", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/usr/lib/python2.7/dist-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/usr/lib/python2.7/dist-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/usr/lib/python2.7/dist-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/usr/lib/python2.7/dist-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/home/zmoelnig/src/deken/deken.hy", line 811, in <module>

  File "/home/zmoelnig/src/deken/deken.hy", line 525, in main
    (defn main []
  File "/home/zmoelnig/src/deken/deken.hy", line 781, in _hy_anon_fn_81

  File "/home/zmoelnig/src/deken/deken.hy", line 551, in _hy_anon_fn_80
    (command arguments))))
  File "/home/zmoelnig/src/deken/deken.hy", line 462, in _hy_anon_fn_71
    (let [[package-filename (make-archive-basename args.repository args.version)]
  File "/home/zmoelnig/src/deken/deken.hy", line 465, in _hy_anon_fn_69
    (gpg-sign-file archive-filename))
  File "/home/zmoelnig/src/deken/deken.hy", line 260, in gpg_sign_file
    (defn gpg-sign-file [filename]
  File "/home/zmoelnig/src/deken/deken.hy", line 266, in _hy_anon_fn_36
    (do-gpg-sign-file filename signfile))))
  File "/home/zmoelnig/src/deken/deken.hy", line 479, in do_gpg_sign_file
    (if (os.path.isfile args.repository)
  File "/home/zmoelnig/src/deken/deken.hy", line 1001, in _hy_anon_fn_34

  File "/home/zmoelnig/src/deken/deken.hy", line 216, in gpg_get_key
    (defn gpg-get-key [gpg]
  File "/home/zmoelnig/src/deken/deken.hy", line 475, in _hy_anon_fn_32
    (archive-dir package-folder package-filename)
  File "/usr/lib/python2.7/dist-packages/gnupg.py", line 1062, in list_keys
    self.decode_errors).splitlines()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 288: ordinal not in range(128)
```

The exception is thrown in the gpg-module and the name for my primary key includes non-ascii characters.
This might well be a problem in `python-gnupg`

**Comment by umlaeute** [comment]
here's a backtrace that does not use the system-wide installation of `python-gnupg` and `hy`:

```python
Deken 0.1
Packaging into stdout-v0.1-(Linux-amd64-64)-externals
Attempting to GPG sign 'stdout-v0.1-(Linux-amd64-64)-externals.tar.gz'
Traceback (most recent call last):
  File "/home/zmoelnig/.deken/virtualenv/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/home/zmoelnig/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/zmoelnig/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/home/zmoelnig/.deken/virtualenv/local/lib/python2.7/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/home/zmoelnig/.deken/virtualenv/local/lib/python2.7/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/home/zmoelnig/.deken/deken.hy", line 811, in <module>
    
  File "/home/zmoelnig/.deken/deken.hy", line 525, in main
    (defn main []
  File "/home/zmoelnig/.deken/deken.hy", line 781, in _hy_anon_fn_81
    
  File "/home/zmoelnig/.deken/deken.hy", line 551, in _hy_anon_fn_80
    (command arguments))))
  File "/home/zmoelnig/.deken/deken.hy", line 462, in _hy_anon_fn_71
    (let [[package-filename (make-archive-basename args.repository args.version)]
  File "/home/zmoelnig/.deken/deken.hy", line 465, in _hy_anon_fn_69
    (gpg-sign-file archive-filename))
  File "/home/zmoelnig/.deken/deken.hy", line 260, in gpg_sign_file
    (defn gpg-sign-file [filename]
  File "/home/zmoelnig/.deken/deken.hy", line 266, in _hy_anon_fn_36
    (do-gpg-sign-file filename signfile))))
  File "/home/zmoelnig/.deken/deken.hy", line 479, in do_gpg_sign_file
    (if (os.path.isfile args.repository)
  File "/home/zmoelnig/.deken/deken.hy", line 3579, in _hy_anon_fn_34
    
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)
```

**Comment by umlaeute** [comment]
i did a minimal test-program that triggers the same problem:
```python
import gnupg
gpg = gnupg.GPG()
print(gpg.list_keys(True))
```

So it seems that the problem is indeed in `python-gnupg` (and most likely deken cannot do anything about it)

**Comment by umlaeute** [comment]
it has already been reported, e.g. https://bugs.debian.org#738483

a quick-fix seems to be to add a line like `gpg.decode_errors='replace'`

**Comment by umlaeute** [comment]
or in hylang:
```hy
(setattr gpg 'decode_errors 'replace))
```

**Comment by chr15m** [comment]
:+1:
